name: Build With CMake
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: webfactory/ssh-agent@v0.7.0
       with:
         ssh-private-key: ${{ secrets.UTILS_PRIVATE }} | ${{ secrets.PB_PRIVATE }} 
     - name: Configure
       run: cmake -DXml_BUILD_TEST=ON -DXml_AUTO_RUN_TEST=ON .

     - name: Build
       run: make
       